import './globals.css'
import { Architects_Daughter, Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const architects_Daughter = Architects_Daughter({
  subsets: ['latin'],
  weight: '400'
})

export const metadata = {
  title: 'Vetra Green',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={architects_Daughter.className}>{children}</body>
    </html>
  )
}
